error[mismatched_arg_count]: this function takes 3 arguments but atleast 4 arguments were supplied
  ┌─ call_side_effects.lua:1:16
  │
1 │ local function foo(a, b, c)
  │                --- note: function defined here
  ·
7 │ foo(a, b, c, call())
  │ ^^^^^^^^^^^^^^^^^^^^ expected 3 arguments

